CREATE TABLE [dbo].[Casting]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[MovieId] INT NOT NULL,
	[PersonId] INT NOT NULL,
	[Role] VARCHAR(100) NOT NULL,
	CONSTRAINT FK_Movie FOREIGN KEY (MovieId) REFERENCES Movie(Id),
	CONSTRAINT FK_Person FOREIGN KEY (PersonId) REFERENCES Person(Id)
)
